input_train_data: "data/bank_train.csv"
input_test_data: "data/bank_etalon.csv"
output_train_data: "data/output/preprocessed_bank_train.csv"
output_test_data: "data/output/preprocessed_bank_test.csv"
preprocessing:
  steps:
    -  replace_email_with_token
    -  to_lower_case
    -  replace_mentions_with_token
    -  replace_hashtags_with_token
    -  remove_rus_stop_words
    -  replace_url_with_token
    -  remove_special_words
    -  remove_punctuation
    -  replace_numbers_with_token
    #-  remove_empty_text

